from datetime import date

EDITING_TIME_LIMIT = 60
LAST_ACCEPTABLE_RELEASE_YEAR = date.today().year + 1
GAME_RESULTS_PER_PAGE = 5
REVIEW_RESULTS_PER_PAGE = 10
USER_RESULTS_PER_PAGE = 15
MAXIMUM_LENGTH_OF_LISTED_TITLE = 50
